#pragma once
#include <imgui.h>
#include <imgui_internal.h>
#include <implot.h>
#include "implot_internal.h"
#include <dxgi1_4.h>
#include <imgui_impl_win32.h>
#include "imgui_impl_dx11.h"
#include <d3d11.h>
#include <misc/cpp/imgui_stdlib.h>
#include <iostream>
#include <string>
#include <fstream>
#include <cstdint>
#include <iomanip>
#include <vector>
#include <array>
#include <map>
#include <chrono>
#include <ctime>   
#include <thread>
#include <filesystem>
#include <stdio.h>
#include <math.h>
#include <Dbt.h>
#include <unordered_map>
#include <wtypes.h>
#include <sstream>
#include <execution>
#include <tchar.h>
#include <random>
#include <dwmapi.h>
#include <unordered_set>
#include <shellapi.h>
#include <dbghelp.h>
#include <functional>
#include <Windows.h>